[project]
name = "marimo-envs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "phisignet", email = "132890251+phisignet@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "marimo[mcp,recommended]>=0.23.7",
]

[build-system]
requires = ["uv_build>=0.10.7,<0.11.0"]
build-backend = "uv_build"
